name: CI/CD for ANC.Api

on:
  pull_request:
    branches:
      - main
    paths:
      - "ANC.Api/**"
      - "ANC.Application/**"
      - "ANC.Domain/**"
      - "ANC.Infrastructure/**"
      - "ANC.sln"

  push:
    branches:
      - main
    paths:
      - "ANC.Api/**"
      - "ANC.Application/**"
      - "ANC.Domain/**"
      - "ANC.Infrastructure/**"
      - "ANC.sln"

jobs:
  ci-checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore dependencies
        run: dotnet restore ANC.sln

      - name: Build solution
        run: dotnet build ANC.sln --configuration Release --no-restore

      # - name: Run tests
      #   run: dotnet test ANC.Tests/ANC.Tests.csproj --no-build

  build-and-push:
    runs-on: ubuntu-latest
    needs: ci-checks
    if: github.event_name == 'push'
    environment: Dockerhub

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create appsettings.Production.json
        run: |
          echo '${{ secrets.ANC_APPSETTINGS }}' > ./ANC.Api/appsettings.Production.json

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set image tags
        id: vars
        run: |
          IMAGE_NAME="anc-api"
          GIT_SHA=$(echo "${GITHUB_SHA}" | cut -c1-7)
          echo "image=${{ secrets.DOCKER_USERNAME }}/$IMAGE_NAME" >> "$GITHUB_OUTPUT"
          echo "sha=$GIT_SHA" >> "$GITHUB_OUTPUT"

      - name: Build Docker image
        run: |
          docker build \
            -t ${{ steps.vars.outputs.image }}:latest \
            -t ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }} \
            -f ./ANC.Api/Dockerfile \
            .

      - name: Push Docker images
        run: |
          docker push ${{ steps.vars.outputs.image }}:latest
          docker push ${{ steps.vars.outputs.image }}:${{ steps.vars.outputs.sha }}
